# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "kiwi_left", "kiwi_right" ]
# include:
#   - board: nice_nano_v2
#     shield: kiwi
#
---
include:
  - board: nice_nano_v2
    shield: kiwi_left
  - board: nice_nano_v2
    shield: kiwi_right
