manifest:
  remotes:
    - name: MaxwellMiddendorf
      url-base: https://github.com/MaxwellMiddendorf
  projects:
    - name: zmk
      remote: MaxwellMiddendorf
      revision: main
      import: app/west.yml
  self:
    path: config

